services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=myapp_development
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web: &web
    build:
      context: .
      dockerfile: docker/development/web/Dockerfile
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
      - node_modules:/app/node_modules
    command: ./bin/dev
    depends_on:
      - db
      - elasticsearch
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/myapp_development
      - RAILS_ENV=development
      - TZ=America/Argentina/Buenos_Aires
    tty: true

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - TZ=America/Argentina/Buenos_Aires
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

volumes:
  bundle_cache:
  db_data:
  elasticsearch_data:
  node_modules: