services:
  web:
    image: yorick:latest
    container_name: yorick-web
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
      - elasticsearch
    volumes:
      - yorick_storage:/rails/storage
      - yorick_logs:/rails/log
    networks:
      - yorick-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/up"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:15-alpine
    container_name: yorick-db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - yorick-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-yorick} -d ${POSTGRES_DB:-yorick}"]
      interval: 10s
      timeout: 5s
      retries: 5

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: yorick-elasticsearch
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - yorick-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  postgres_data:
    driver: local
  elasticsearch_data:
    driver: local
  yorick_storage:
    driver: local
  yorick_logs:
    driver: local

networks:
  yorick-network:
    driver: bridge
