services:
  db:
    image: postgres:15
    container_name: myapp-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myapp_development
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web: &web
    build:
      context: .
      dockerfile: docker/development/web/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
      # - node_modules:/app/node_modules
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db
    environment:
      - RAILS_ENV=development
      - WEBPACKER_DEV_SERVER_HOST=webpacker
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/myapp_development

  # webpacker:
  #   <<: *web
  #   command: sh -c "rm -rf public/packs && ./bin/webpack-dev-server --inline --hot true"
  #   ports:
  #     - "3035:3035"
  #   logging:
  #     driver: none

  # elasticsearch:
  #   image: elasticsearch:7.17.27
  #   environment:
  #     - cluster.name=docker-cluster
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #     - xpack.security.enabled=false
  #     - discovery.type=single-node
  #   # ulimits:
  #   #   memlock:
  #   #     soft: -1
  #   #     hard: -1
  #   volumes:
  #     - elasticsearch_data:/usr/share/elasticsearch/data
  #   ports:
  #     - "9200:9200"
  #   logging:
  #     driver: none

volumes:
  bundle_cache:
  db_data:
  # elasticsearch_data:
  # node_modules: