name: Retag and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  retag:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history to access parent commits

      - name: Get commit SHA for retagging
        id: commit_sha
        run: |
          # For squash merges, use the current commit SHA
          # For regular merges, use the first parent (PR head)
          if git rev-parse HEAD^1 >/dev/null 2>&1; then
            # Regular merge - get the PR head SHA
            COMMIT_SHA=$(git rev-parse HEAD^1)
          else
            # Squash merge or single commit - use current SHA
            COMMIT_SHA=$(git rev-parse HEAD)
          fi
          echo "commit_sha=$COMMIT_SHA" >> $GITHUB_OUTPUT
          echo "Using commit SHA: $COMMIT_SHA"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull image built by PR workflow
        run: |
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.commit_sha.outputs.commit_sha }}

      - name: Tag image as 'main' and 'latest'
        run: |
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.commit_sha.outputs.commit_sha }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.commit_sha.outputs.commit_sha }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Push 'main' and 'latest' tags
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Output image tags
        run: |
          echo "Retagged and pushed images with tags: main, latest"
          echo "Source commit SHA: ${{ steps.commit_sha.outputs.commit_sha }}"
